# Docker Compose configuration for development environment
services:
  # Web service configuration
  web:
    # Build configuration
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    # Port mapping for Next.js
    ports:
      - "3000:3000"
    # Volume mounts for development
    volumes:
      - .:/app  # Mount current directory
      - node_modules:/app/node_modules  # Named volume for node_modules
    # Load environment variables
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    # Enable hot reload for development
    command: npm run dev
    # Container health monitoring
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

# Named volumes definition
volumes:
  node_modules:  # Persistent volume for node_modules
