# Development Docker Compose Configuration
# This file is optimized for local development with hot-reloading and debugging

version: '3.8'

services:
  # Main application service
  app:
    # Build from local Dockerfile optimized for development
    build:
      context: ..
      dockerfile: docker/Dockerfile
    
    # Enable container restarts
    restart: unless-stopped
    
    # Map container port 3000 to host
    ports:
      - "3000:3000"
    
    # Mount local directories for development
    volumes:
      # Source code
      - ..:/app
      # Node modules (cached)
      - node_modules:/app/node_modules
      # Next.js build cache
      - next-cache:/app/.next/cache
    
    # Load environment variables
    env_file:
      - ../.env.development
    
    # Set development environment variables
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=3000
      # Enable Next.js debugging
      - NODE_OPTIONS=--inspect
    
    # Health check to ensure container is running properly
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    
    # Enable hot reload for development
    command: npm run dev
    
    # Development tools
    stdin_open: true  # Keep STDIN open for debugging
    tty: true        # Allocate a pseudo-TTY

# Define named volumes for persistence
volumes:
  # Store node_modules to avoid reinstalling on every build
  node_modules:
  # Store Next.js build cache for faster rebuilds
  next-cache:
