version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
      args:
        BUILD_ENV: staging
    image: contentful-mux-nextjs-starter:staging
    ports:
      - "3000:3000"
    # Load environment variables
    env_file:
      - ../.env.staging
    environment:
      - NODE_ENV=staging
      - HOSTNAME=0.0.0.0
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
